"""added paypal transaction table

Revision ID: 2488c1fd79c1
Revises: cc1b33ce20b2
Create Date: 2024-10-27 16:18:15.049327

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2488c1fd79c1"
down_revision = "cc1b33ce20b2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "paypal",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("paypal_transaction_id", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("internal_user_id", sa.Integer(), nullable=False),
        sa.Column("paypal_customer_acc_id", sa.String(), nullable=True),
        sa.Column("transaction_amount", sa.Float(), nullable=False),
        sa.Column("transaction_currency", sa.String(), nullable=False),
        sa.Column("reference_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["internal_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("paypal")
    # ### end Alembic commands ###
