"""Initial migration.

Revision ID: 6af748fd2893
Revises:
Create Date: 2024-10-12 02:53:11.073247

"""

import sqlalchemy as sa
from alembic import op
from decouple import config

# revision identifiers, used by Alembic.
revision = "6af748fd2893"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("part_number", sa.String(length=32), nullable=False),
        sa.Column("ean", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("specs", sa.JSON(), nullable=True),
        sa.Column("stocks", sa.Integer(), nullable=False),
        sa.Column("sold_pieces", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("part_number"),
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("ship_to", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum("new", "dispatched", "shipped", "received", name="orderstatus"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=40), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=25), nullable=False),
        sa.Column("first_name", sa.String(length=255), nullable=False),
        sa.Column("last_name", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum("admin", "regular", "manager", "dispatcher", name="userrole"),
            nullable=False,
        ),
        sa.Column(
            "number_of_orders",
            sa.Integer(),
            nullable=False,
            default=0,
            server_default="0",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )

    op.execute(
        f"INSERT users (email, password, username, first_name, last_name, role)"
        f"VALUES (admin@admin.com, {config('admin_pass')}, admin, system, admin, admin)"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("orders")
    op.drop_table("items")
    op.execute("DROP TYPE userrole;")
    op.execute("DROP TYPE orderstatus;")
    # ### end Alembic commands ###
