"""added new colum product_sold_price

Revision ID: c8e20d4de9f8
Revises: 7ad22b75407c
Create Date: 2024-10-19 03:07:59.290395

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c8e20d4de9f8"
down_revision = "7ad22b75407c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("client_basket", schema=None) as batch_op:
        batch_op.add_column(sa.Column("product_sold_price", sa.Float(), nullable=False))
        batch_op.create_foreign_key("fk_item_id", "items", ["product_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("client_basket", schema=None) as batch_op:
        batch_op.drop_constraint("fk_item_id", type_="foreignkey")
        batch_op.drop_column("product_sold_price")

    # ### end Alembic commands ###
