"""created log table + columns update/created to other models

Revision ID: cb5b22172d16
Revises: 4ca3f1e2cadd
Create Date: 2024-10-23 01:03:00.197337

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cb5b22172d16"
down_revision = "4ca3f1e2cadd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("prod_id", sa.Integer(), nullable=True),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column("log_info", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["prod_id"],
            ["items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.execute(
        "ALTER TABLE logs ALTER COLUMN order_id DROP NOT NULL, ALTER COLUMN prod_id DROP NOT NULL;"
    )
    with op.batch_alter_table("country", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(),
                server_default=sa.text("now()"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "updated_at",
                sa.DateTime(),
                server_default=sa.text("now()"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column("last_update_by", sa.Integer(), default=1, server_default="1")
        )
        batch_op.create_foreign_key(
            "update_by_user", "users", ["last_update_by"], ["id"]
        )

    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(),
                server_default=sa.text("now()"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "updated_at",
                sa.DateTime(),
                server_default=sa.text("now()"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column("last_update_by", sa.Integer(), default=1, server_default="1")
        )
        batch_op.create_foreign_key(
            "update_by_user", "users", ["last_update_by"], ["id"]
        )

    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "updated_at",
                sa.DateTime(),
                server_default=sa.text("now()"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column("last_update_by", sa.Integer(), default=1, server_default="1")
        )
        batch_op.create_foreign_key(
            "update_by_user", "users", ["last_update_by"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_constraint("update_by_user", type_="foreignkey")
        batch_op.drop_column("last_update_by")
        batch_op.drop_column("updated_at")

    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.drop_constraint("update_by_user", type_="foreignkey")
        batch_op.drop_column("last_update_by")
        batch_op.drop_column("updated_at")
        batch_op.drop_column("created_at")

    with op.batch_alter_table("country", schema=None) as batch_op:
        batch_op.drop_constraint("update_by_user", type_="foreignkey")
        batch_op.drop_column("last_update_by")
        batch_op.drop_column("updated_at")
        batch_op.drop_column("created_at")

    op.drop_table("logs")
    # ### end Alembic commands ###
