"""Added new column to orders - currency

Revision ID: cc1b33ce20b2
Revises: cb5b22172d16
Create Date: 2024-10-27 11:20:36.023338

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cc1b33ce20b2"
down_revision = "cb5b22172d16"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("country", schema=None) as batch_op:
        batch_op.alter_column(
            "last_update_by", existing_type=sa.INTEGER(), nullable=False
        )

    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.alter_column(
            "last_update_by", existing_type=sa.INTEGER(), nullable=False
        )

    with op.batch_alter_table("logs", schema=None) as batch_op:
        batch_op.alter_column("prod_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("order_id", existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "order_currency", sa.String(), server_default="EUR", nullable=False
            )
        )
        batch_op.alter_column(
            "last_update_by", existing_type=sa.INTEGER(), nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.alter_column(
            "last_update_by", existing_type=sa.INTEGER(), nullable=True
        )
        batch_op.drop_column("order_currency")

    with op.batch_alter_table("logs", schema=None) as batch_op:
        batch_op.alter_column("order_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("prod_id", existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.alter_column(
            "last_update_by", existing_type=sa.INTEGER(), nullable=True
        )

    with op.batch_alter_table("country", schema=None) as batch_op:
        batch_op.alter_column(
            "last_update_by", existing_type=sa.INTEGER(), nullable=True
        )

    # ### end Alembic commands ###
