"""splitted ship to to country_city_zipcode

Revision ID: df571be6c40c
Revises: 208847107b50
Create Date: 2024-10-18 22:50:43.269520

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "df571be6c40c"
down_revision = "208847107b50"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("to_country", sa.String(length=255), nullable=False)
        )
        batch_op.add_column(sa.Column("to_city", sa.String(length=255), nullable=False))
        batch_op.add_column(
            sa.Column("to_zipcode", sa.String(length=255), nullable=False)
        )
        batch_op.drop_column("ship_to")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "ship_to", sa.VARCHAR(length=255), autoincrement=False
            )
        )
        batch_op.drop_column("to_zipcode")
        batch_op.drop_column("to_city")
        batch_op.drop_column("to_country")

    # ### end Alembic commands ###
