"""changed eans values from int to string with constrain of 13 digits

Revision ID: e02db421da03
Revises: 6af748fd2893
Create Date: 2024-10-13 22:36:46.816609

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e02db421da03"
down_revision = "6af748fd2893"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.alter_column(
            "ean",
            existing_type=sa.INTEGER(),
            type_=sa.String(length=13),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.alter_column(
            "ean",
            existing_type=sa.String(length=13),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
